"""adding nullable to some fields in User

Revision ID: 06992bce8f1f
Revises: 958e75db63e0
Create Date: 2026-05-03 11:46:37.549165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "06992bce8f1f"
down_revision: Union[str, Sequence[str], None] = "958e75db63e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("users", "bio", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "bio", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
