# Generated by Django 6.0.6 on 2026-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Досвід роботи', 'verbose_name_plural': 'Досвід роботи'},
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку (для сортування)'),
        ),
    ]
