# Generated by Django 6.0.6 on 2026-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='users', through='courses.UserCourse', to='courses.course', verbose_name='Курси'),
        ),
    ]
