# Generated by Django 6.0.6 on 2026-07-24 17:32

import django.db.models.deletion
import Python_Web.hw64.project_gallery.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='original_image',
            field=models.ImageField(upload_to='gallery/original/', validators=[Python_Web.hw64.project_gallery.validators.validate_image_security_and_dimensions]),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='project_gallery.project'),
        ),
    ]
