# Generated by Django 6.0.6 on 2026-07-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_gallery', '0002_project_owner_alter_projectgallery_original_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
