"""adding lazy select relationship

Revision ID: 20e7f68b06d8
Revises: 2af90f1334ff
Create Date: 2026-05-03 11:51:42.167870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "20e7f68b06d8"
down_revision: Union[str, Sequence[str], None] = "2af90f1334ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
