"""add_health_status_to_animal

Revision ID: 612345b16570
Revises: 2bbd53f56901
Create Date: 2026-04-24 20:49:43.318681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "612345b16570"
down_revision: Union[str, Sequence[str], None] = "2bbd53f56901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animals",
        sa.Column(
            "health_status",
            sa.String(length=15),
            server_default="healthy",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animals", "health_status")
    # ### end Alembic commands ###
