# Generated by Django 6.0.6 on 2026-07-13 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, verbose_name='Назва проекту')),
                ('project_type', models.CharField(choices=[('web3_automation', 'Web3 & Crypto Automation'), ('backend_dev', 'Python Backend Development'), ('frontend_dev', 'Frontend Development (HTML/CSS/JS/React)'), ('telegram_bot', 'Telegram Bot / Parser Automation'), ('fullstack_dev', 'Fullstack Application'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Тип проекту')),
                ('description', models.TextField(verbose_name='Технічне завдання (опис брифу)')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет (USD)')),
                ('timeline', models.CharField(max_length=100, verbose_name='Бажані терміни')),
                ('contacts', models.CharField(max_length=200, verbose_name="Контакти для зв'язку")),
                ('status', models.CharField(choices=[('pending', 'Очікує розгляду'), ('in_progress', 'В процесі розробки'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Замовник')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
